const constants = {
  AUTHORED_POSTS_COLLECTION: 'authoredPosts',
  FEED_CACHE_TIME: 30_000,
  PAGINATION_COUNT: 10,
  POST_CACHE_TIME: 10_000,
  POSTS_COLLECTION: 'posts',
  REPLIES_CACHE_TIME: 10_000,
  REVALIDATE_TIME: 10,
  USERS_COLLECTION: 'users',
}

export default constants
