const constants = {
  AUTHORED_POSTS_COLLECTION: 'authoredPosts',
  BRAND_NAME: 'Fameless',
  FEED_CACHE_TIME: 30_000,
  HASHTAG_LIST_CACHE_TIME: 30_000,
  HASHTAG_REGEX: /\B(#[a-zA-Z0-9_%]{1,})/g,
  PAGINATION_COUNT: 10,
  POST_AUTHOR_CACHE_TIME: Infinity,
  POST_CACHE_TIME: 10_000,
  POSTS_COLLECTION: 'posts',
  REPLIES_CACHE_TIME: 10_000,
  REVALIDATE_TIME: 10,
  USERS_COLLECTION: 'users',
}

export default constants
