export default {
  APP_URL: 'https://fameless.app',
  AUTHORED_POSTS_COLLECTION: 'authoredPosts',
  AUTHORED_REPLIES_COLLECTION: 'authoredReplies',
  EMAIL_VERIFICATION_EMAIL_TEMPLATE_ID: 'd-8d25bc3f764e478cbb2a4ec05a458b4a',
  EMAIL_VERIFICATION_REQUESTS_COLLECTION: 'emailVerificationRequests',
  PASSWORD_RESET_EMAIL_TEMPLATE_ID: 'd-e65568311be84ceda0b5cbc47dd368b9',
  PASSWORD_RESET_REQUESTS_COLLECTION: 'passwordResetRequests',
  POSTING_REQUIRES_ACCOUNT: false,
  POSTS_COLLECTION: 'posts',
  USERS_COLLECTION: 'users',
}
